---
# Additional packages
#additional_packages:
#  - curl

user: '{{ current_user }}'
group_name: '{{ current_user }}'
user_home_path: "{{ lookup('env','HOME') }}"

# Git global config
#git_name:
#git_email:

java_version: 8